#!/usr/bin/env bash
#
# format ports commits

for dir in */; {
    . "${dir}Pkgfile" 2> /dev/null && {
        # compare versions
        var=$version-$release
        cur=$(prt-get current "$name")

        git add "$dir"

        # commit with the relevant message
        case $cur in
           '') git commit -m "add $name";;
            $var) ;; # do nothing
            *) git commit -m "$name : $cur -> $var"
        esac
    }
}
