#!/usr/bin/env bash
#
# format ports commits

for pkg in *; {
    [[ -d $pkg ]] && {
        . "$pkg/Pkgfile" 2> /dev/null || {
            echo "${0##*/} : can't source the Pkgfile for '$pkg'" >&2
            exit 1
        }

        # compare versions
        var=$version-$release
        cur=$(prt-get printf '%v-%r' --filter="$name")

        git add "$pkg"

        [[ $cur           ]] || { git commit -m "add $name"           ; break; }
        [[ $cur != "$var" ]] && { git commit -m "$name : $cur -> $var"; break; }
    }
}
