#!/usr/bin/env bash
#
# format ports commits

for pkg in */; {
    pkg=${pkg%?}

    . "$pkg/Pkgfile" 2> /dev/null || {
        echo "${0##*/} : can't source the Pkgfile for '$pkg'" >&2
        exit 1
    }

    # compare versions
    var=$version-$release
    cur=$(prt-get printf '%v-%r' --filter="$name")

    git add "$pkg"

    # commit with the relevant message
    case $cur in
       '') git commit -m "add $name";;
        $var) ;; # do nothing
        *) git commit -m "$name : $cur -> $var"
    esac
}
