#!/usr/bin/env bash
#
# create package from installed files

read -r version release < <(
    prt-get printf '%v %r' --filter="$1"
)

[[ $version && $release ]] || {
    echo "usage : ${0##*/} [package]" >&2
    exit 1
}

pwd=$PWD

cd /; IFS=$'\n'

tar czvf "$pwd/$1#$version-$release.pkg.tar.gz" $(
    while read -r file; do
        [[ -d $file ]] || echo "$file"
    done < <(pkginfo -l "$1")
)
