#!/usr/bin/env bash
#
# list ports that aren't sourced from github

for pkg in *; {
    [[ -d $pkg ]] && {
        . "$pkg/Pkgfile" || {
            echo "${0##*/} : can't source the Pkgfile for '$pkg'" >&2
            exit 1
        }

        for source in "${source[@]}"; {
            [[ $source =~ github\.com ]] && continue 2
        }

        echo "$pkg"
    }
}
