#!/usr/bin/env bash
#
# list ports that aren't sourced from github

shopt -s globstar

for file in **; {
    [[ -f $file && $file =~ Pkgfile$ ]] && {
        . "$file"

        for source in "${source[@]}"; {
            [[ $source =~ github\.com ]] && continue 2
        }

        echo "${file%%/*}"
    }
}
