#!/usr/bin/env bash
#
# list packages that could be removed

while read -r pkg; do
    {
        path=$(prt-get path "$pkg")

        for repo; {
            [[ $path =~ $repo/$pkg$ ]] && break 2
        } || echo "$pkg"
    } &
done < <(prt-get listorphans)

wait
