#!/usr/bin/env bash
#
# list packages that could be removed

while read -r pkg; do
    {
        [[ $(prt-get info "$pkg") =~ Path:\ *([^$'\n']*) ]] && {
            var=${BASH_REMATCH[1]}

            for repo; {
                [[ $var =~ $repo$ ]] && break 2
            } || echo "$pkg"
        }
    } &
done < <(prt-get listorphans)

wait
