#!/usr/bin/env bash
#
# list packages that could be removed

# ignore repos
ignore=(turquoise core)

while read -r pkg; do
    while read -r line; do
        [[ $line =~ ^Path ]] && {
            for repo in "${ignore[@]}"; {
                [[ $repo =~ "${line##*/}" ]] && continue 2
            }

            echo "$pkg"

            break
        }
    done < <(prt-get info "$pkg") &
done < <(prt-get listorphans)

wait
