#!/bin/bash
#
# list missing dependencies

declare -A installed aliases

# store aliases
while IFS=': ' read -r alias orig; do
    aliases[$alias]=$orig
done < /var/lib/pkg/prt-get.aliases

list=$(prt-get listinst)

# store installed packages
while read -r pkg; do
    [[ ${aliases[$pkg]} ]] &&
        installed[${aliases[$pkg]}]=1

    installed[$pkg]=1
done <<< $list

# find missing dependencies
while read -r pkg; do
    for dependency in $(prt-get quickdep "$pkg"); {
        ((installed[$dependency])) || echo "$dependency"
    } &
done <<< $list

wait
