#!/usr/bin/env bash
#
# find missing libraries

list=$(pkginfo -l "$1" 2> /dev/null) || {
    echo "usage : ${0##*/} [package]" >&2
    exit 1
}

while read -r line; do
    [[                               \
        $line =~ (.*)' => '(.*)\  && \
        ${BASH_REMATCH[2]} == not    \
    ]] &&
        echo "${BASH_REMATCH[1]}"
done < <(
    cd /; IFS=$'\n'

    ldd $list 2> /dev/null
)
