#!/usr/bin/env bash
#
# find some of the dependencies missing from the list

list=$(pkginfo -l "$1" 2> /dev/null) || {
    echo "usage : ${0##*/} [package]" >&2
    exit 1
}

declare -A array

while read -r line; do
        [[                                                             \
            $line =~ '=> '(.*)\  &&                                    \
            $(prt-get fsearch --full "${BASH_REMATCH[1]}") =~ ([^/]+): \
        ]] &&
            array[${BASH_REMATCH[1]}]=1
done < <(
    cd /; IFS=$'\n'

    ldd $list 2> /dev/null
)

depends=$(prt-get quickdep "$1")

for pkg in "${!array[@]}"; {
    for dep in $depends glibc gcc; {
        [[ $pkg == "$dep" ]] && continue 2
    }

    echo "$pkg"
}
