#!/usr/bin/env bash
#
# print package size

(($#)) && infos=$(prt-get info "$1" 2> /dev/null) || {
    echo "usage : ${0##*/} [package]" >&2
    exit 1
}

units=(B K M G T)

# get package size
while IFS=: read -r var val; do
    [[ $var =~ ^Path ]] && {
        path=${val// }

        while read -r _ _ file; do
            # handle .footprint properly
            file=${file% ->*}
            file=/${file% (*)}

            [[ -f $file ]] &&
                ((size += `stat -c '%s' "$file"`)) 2> /dev/null
        done < "$path/$1/.footprint"

        break
    }
done <<< $infos

# make size human readable
for ((b = size; b > 1024; b /= 1024, i++)) {
    d=.$((b % 1024 * 10 / 1024))
}

echo "$b$d${units[i]}"
