#!/usr/bin/env bash
#
# print package size

(($#)) || {
    echo "usage : ${0##*/} [package]" >&2
    exit 1
}

units=(B K M G T)

# get package size
while read -r line; do
    [[ $line =~ ^Path ]] && {
        IFS=: read -r _ path <<< $line

        while read -r _ _ file; do
            # handle .footprint properly
            file=${file% ->*}
            file=${file% (*)}

            ((size += `stat --printf='%s' "/$file"`))
        done < "${path// }/$1/.footprint"

        break
    }
done < <(prt-get info "$1" 2> /dev/null)

# make size human readable
for ((; c > 1024; c /= 1024)) {
    ((i++))
}

echo "${size:-0}${units[i]}"
