#!/usr/bin/env bash
#
# print package size

path=$(prt-get printf '%p' --filter="$1")

(($#)) && [[ $path ]] || {
    echo "usage : ${0##*/} [package]" >&2
    exit 1
}

# get package size
while read -r cur; do
    ((size += cur))
done < <(
    IFS=$'\n'
    stat -c '%s' $(
        while IFS=$'\t' read -r perms _ file; do
            [[ $perms =~ ^d ]] || {
                # handle .footprint properly
                file=${file% ->*}
                file=/${file% (*)}

                echo "$file"
            }
        done < "$path/$1/.footprint"
    ) 2> /dev/null
)

# make size human readable
units=(B K M G T)

for ((b = size; b > 1024; b /= 1024, i++)) {
    d=.$((b % 1024 * 10 / 1024))
}

echo "$b$d${units[i]}"
