#!/usr/bin/env bash
#
# check packages for updates

display() {
    local -n var=$2

    echo "$1"

    for pkg in "${!var[@]}"; {
        echo "$pkg : ${var[$pkg]}"
    }
}

declare -A a b

for pkg in *; {
    [[ -d $pkg ]] && {
        cpt=
        cur=$(prt-get printf '%v' --filter="$pkg")

        while read -r line; do
            [[ $line =~ text ]] && ((++cpt == 5)) && {
                # parse svg
                line=${line#*>}
                line=${line%<*}
                var=${line##*, }

                break
            }
        done < <(curl -s "https://repology.org/badge/latest-versions/$pkg.svg")

        # compare versions
        if   [[ $var ==      - ]]; then b[$pkg]="$cur -> $var"
        elif [[ $var != "$cur" ]]; then a[$pkg]="$cur -> $var"; fi
    }
}

display "has a different version :" a
echo
display "has no existing version :" b
