#!/usr/bin/env bash
#
# check packages for updates

# build list of packages
for pkg in */; {
    tmp+=("${pkg%?}")
}

while read -r line; do
    # parse svgs to compare versions
    [[ $line =~ middle\"\>.*middle\"\>([^ ,]*).*\<\/text ]]

    var=${BASH_REMATCH[1]}
    pkg=${tmp[i++]}

    . "$pkg/Pkgfile" 2> /dev/null || {
        echo "${0##*/} : can't source the Pkgfile for '$pkg'" >&2
        exit 1
    }

    case $var in
        -) n_ver+=("$pkg : $version -> $var");;
        $version) ;; # do nothing
        *) y_ver+=("$pkg : $version -> $var")
    esac
done < <(
    # build list of urls
    curl -w '\n' -s $(
        printf 'https://repology.org/badge/latest-versions/%s.svg ' "${tmp[@]}"
    ))

printf '%s\n%s\n' "${y_ver[@]}" "${n_ver[@]}"
