#!/bin/bash

cd_git_repo() {
    while [[ $PWD != / ]]; do
        if [[ -d $PWD/.git ]]; then
            return 0
        fi

        cd ..
    done

    return 1
}

cd_git_repo || {
    echo "error : '${0##*/}' must be run from a git repo" >&2

    exit 1
}

declare -A cache

repo=${PWD##*/}

while IFS=' ' read -r path name version release; do
    if [[ ${path##*/} == "$repo" ]]; then
        cache[$name]=$version-$release
    fi
done <<< $(prt-get printf '%p %n %v %r\n')

for dir in */; do
    if source "$dir/Pkgfile" 2> /dev/null; then
        # compare versions
        local_version=$version-$release
        global_version=${cache[$name]}

        git add "$dir"

        # commit with relevant message
        case $global_version in
            '') git commit -m "add $name";;
            $local_version) ;; # do nothing
             *) git commit -m "$name : $global_version -> $local_version"
        esac
    fi
done
