#!/bin/bash
#
# prtcommit - commit ports changes to git with a formatted message

declare -A array

while read -r name version release; do
    array[$name]=$version-$release
done <<< $(prt-get printf '%n %v %r\n')

for dir in */; {
    . "${dir}Pkgfile" 2> /dev/null && {
        # compare versions
        var=$version-$release
        cur=${array[$name]}

        git add "$dir"

        # commit with the relevant message
        case $cur in
            '') git commit -m "add $name";;
             "$var") ;; # do nothing
             *) git commit -m "$name : $cur -> $var"
        esac
    }
}
