#!/bin/bash
#
# prtexport - export an installed package to a crux package

die() {
    printf '%s\n' "${1:-usage : ${0##*/} <package>}" >&2
    exit 1
}

version=$(prt-get current "$1") ||
    die

mapfile -t <<< $(
    while read -r file; do
        # strip directories
        [[ $file =~ \/$ ]] ||
            printf '%s\n' "$file"
    done <<< $(pkginfo -l "$1"))

tar czvf "$1#$version.pkg.tar.gz" -C / -- "${MAPFILE[@]}"
