#!/bin/sh
#
# prtexpot - export an installed package to a crux package

version=$(prt-get current "$1") || {
    echo "usage : ${0##*/} <package>" >&2
    exit 1
}

IFS='
'

tar czvf "$1#$version.pkg.tar.gz" -C / -- $(
    pkginfo -l "$1" |
        while read -r file; do
            case $file in
                */) continue
            esac

            echo "$file"
        done
)
