#!/bin/bash
#
# prtlastcommit - set Pkgfile to the last commit available from git{hub,lab}

die() {
    printf '%s\n' "$1" >&2
    exit 1
}

# get package informations
. Pkgfile 2> /dev/null ||
    die 'error : failed to source Pkgfile'

[[ $commit ]] ||
    die 'error : wrong package format'

# get repo informations
trap 'rm -rf "$name"' EXIT

[[ $source =~ (http.?://([^/]+/){3}) ]] &&
    git clone "${BASH_REMATCH[1]}" --depth=1 "$name" 2> /dev/null ||
        die 'error : failed to clone source'

read -r sha time _ _ <<< \
    $(git --git-dir="$name/.git" log --format='%H %ci')

[[ $sha == "$commit" ]] &&
    die 'error : already up to date'

# update pkgfile
time=${time//-}

printf '%s\n' "$(
    while IFS= read -r line; do
        case $line in
            commit*)  line=commit=$sha;;
            version*) line=version=$time
        esac

        printf '%s\n' "$line"
    done < Pkgfile
)" > Pkgfile
