#!/bin/bash
#
# prtmissingdeps - find dependencies that are missing from the system

declare -A installed aliases missing

# store aliases
while IFS=': ' read -r alias orig; do
    aliases[$alias]=$orig
done < /var/lib/pkg/prt-get.aliases

list=$(prt-get listinst)

# store installed packages
while read -r pkg; do
    [[ ${aliases[$pkg]} ]] &&
        installed[${aliases[$pkg]}]=1

    installed[$pkg]=1
done <<< $list

# find missing dependencies
while read -r pkg; do
    for dependency in $(prt-get quickdep "$pkg"); {
        ((installed[$dependency])) || missing[$dependency]=
    }
done <<< $list

printf '%s\n' "${!missing[@]}"
