#!/bin/bash
#
# prtmissingfiles - find files that were installed by packages but are now missing from the system

die() {
    printf '%s\n' "${1:-usage : ${0##*/} <package>}" >&2
    exit 1
}

list=$(pkginfo -l "$1" 2> /dev/null) ||
    die

while read -r file; do
    [[ -e /$file ]] ||
        printf '/%s\n' "$file"
done <<< $list
