#!/bin/bash
#
# prtmissing - find packages that are missing from available ports

declare -A array

while read -r pkg; do
    array[$pkg]=1
done <<< $(prt-get list)

while read -r pkg; do
    [[ ${array[$pkg]} ]] || echo "$pkg"
done <<< $(prt-get listinst)
