#!/bin/bash
#
# prtmissinglibs - find packages that were linked to a package but are missing from the system

die() {
    printf '%s\n' "${1:-usage : ${0##*/} <package>}" >&2
    exit 1
}

list=$(pkginfo -l "$1" 2> /dev/null) ||
    die

mapfile -t <<< $list

declare -A array

while read -r line; do
    [[
        $line =~ (.*)' => '(.*)\  &&
        ${BASH_REMATCH[2]} == not
    ]] &&
        array[${BASH_REMATCH[1]}]=1
done <<< $(
    cd /

    ldd -- "${MAPFILE[@]}" 2> /dev/null)

for lib in "${!array[@]}"; {
    printf '%s\n' "$lib"
}
