#!/bin/bash

declare -A array

shopt -s globstar

for file in /usr/ports/**; {
    [[ $file =~ \/Pkgfile ]] && {
        prt=${file%/*}
        prt=${prt##*/}
        array[$prt]=1
    }
}

shopt -u globstar

while read -r pkg; do
    [[ ${array[$pkg]} ]] ||
        echo "$pkg"
done <<< $(prt-get listinst)
