#!/bin/bash
#
# prtmissinglibs - find libraries that were linked to a package but are missing from the system

list=$(pkginfo -l "$1" 2> /dev/null) || {
    echo "usage : ${0##*/} <package>" >&2
    exit 1
}

declare -A array

while read -r line; do
    [[
        $line =~ (.*)' => '(.*)\  &&
        ${BASH_REMATCH[2]} == not
    ]] &&
        array[${BASH_REMATCH[1]}]=
done < <(
    cd /; IFS=$'\n'

    ldd $list 2> /dev/null
)

for lib in "${!array[@]}"; {
    echo "$lib"
}
