#!/bin/bash
#
# prtnewdeps - find dependencies that needs to be installed for a package

list=$(prt-get depends "$1" 2> /dev/null) || {
    echo "usage : ${0##*/} <package>" >&2
    exit 1
}

while read -r line; do
    [[ $line =~ ^'[ ] '(.*) ]] &&
        echo "${BASH_REMATCH[1]}"
done <<< $list
