#!/bin/bash
#
# list dependencies that would have to be installed

list=$(prt-get depends "$1" 2> /dev/null) || {
    echo "usage : ${0##*/} [package]" >&2
    exit 1
}

while read -r line; do
    [[ $line =~ ^'[ ] '(.*) ]] &&
        echo "${BASH_REMATCH[1]}"
done <<< $list
