#!/bin/bash
#
# prtorphans - find packages that can be safely removed with a package

die() {
    printf '%s\n' "${1:-usage : ${0##*/} <package>}" >&2
    exit 1
}

dependencies=$(prt-get quickdep "$1" 2> /dev/null) ||
    die

for dependency in $dependencies; {
    # check if all dependents are dependencies
    while read -r dependent; do
        for package in $dependencies; {
            [[ $dependent == "$package" ]] && break
        } || continue 2
    done <<< $(prt-get dependent --recursive "$dependency")

    printf '%s\n' "$dependency"
}
