#!/bin/bash
#
# prtorphaned - find packages that can be safely removed

declare -A aliases

while IFS=': ' read -r key val; do
    aliases[$key]=$var
done < /var/lib/pkg/prt-get.aliases

declare -A paths

while read -r name path; do
    paths[$name]=$path/$name
done <<< $(prt-get printf '%n %p\n')

while read -r pkg; do
    [[ ${aliases[$pkg]} && -n \
        $(prt-get dependent "${aliases[$pkg]}") ]] &&
        continue

    for repo; {
        [[ ${paths[$pkg]} =~ $repo/$pkg$ ]] && break
    } || echo "$pkg"
done <<< $(prt-get listorphans)
