#!/bin/bash
#
# prtomitteddeps - find dependencies that were omitted from a package description

die() {
    printf '%s\n' "${1:-usage : ${0##*/} <package>}" >&2
    exit 1
}

list=$(pkginfo -l "$1" 2> /dev/null) ||
    die

declare -A files packages

# build a database
while read -r line; do
    [[ $line ]] || {
        tmp=0
        continue
    }

    ((tmp)) || {
        tmp=1
        pkg=$line
        continue
    }

    files[/$line]=$pkg
done < /var/lib/pkg/db

mapfile -t <<< $list

while read -r line; do
    [[
        $line =~ '=> '(.*)\       &&
        ${files[${BASH_REMATCH[1]}]} \
    ]] &&
        packages[${files[${BASH_REMATCH[1]}]}]=1
done <<< $(
    cd /

    ldd -- "${MAPFILE[@]}" 2> /dev/null
)

depends=$(prt-get quickdep "$1")

for pkg in "${!packages[@]}"; {
    # https://crux.nu/Main/PortGuidelines#ntoc2
    for dep in $depends glibc gcc; {
        [[ $pkg == "$dep" ]] && continue 2
    }

    printf '%s\n' "$pkg"
}
