#!/bin/bash
#
# prtsize - find size of an installed package

die() {
    printf '%s\n' "${1:-usage : ${0##*/} <package>}" >&2
    exit 1
}

# get list of files
list=$(pkginfo -l "$1" 2> /dev/null) ||
    die

while read -r file; do
    [[ $file =~ \/$ ]] ||
        files+=("/$file")
done <<< $list

# get package size
while read -r size _; do
    out=$size
done <<< $(du -c -h "${files[@]}")

printf '%s\n' "$out"
