#!/bin/bash
#
# prtsize - find size of an installed package

die() {
    printf '%s\n' "${1:-usage : ${0##*/} <package>}" >&2
    exit 1
}

# get list of files
list=$(pkginfo -l "$1" 2> /dev/null) ||
    die

while read -r file; do
    [[ $file =~ \/$ ]] ||
        files+=("/$file")
done <<< $list

# get package size
while read -r size; do
    ((sum += size))
done <<< $(stat -c '%s' -- "${files[@]}" 2> /dev/null)

# make size human readable
units=(B K M G T)

for ((b = sum; b > 1024; b /= 1024, ++i)) {
    d=.$((b % 1024 * 10 / 1024))
}

printf '%s%s%s\n' "$b" "$d" "${units[i]}"
