#!/bin/bash
#
# prtversion - compare local versions with versions from repology

die() {
    printf '%s\n' "${1:-usage : ${0##*/} <repo>}" >&2
    exit 1
}

display() {
    declare -n tmp=$1

    for msg in "${tmp[@]}"; {
        printf '%s\n' "$msg"
    }
}

(($#)) ||
    die

# build a list of packages
while read -r pkg ver path; do
    [[ $ver == git ]] ||
        for repo; {
            [[ $path =~ /$repo$ ]] && {
                tmp_pkg+=("$pkg")
                tmp_ver+=("$ver")
            }
        }
done <<< $(prt-get printf '%n %v %p\n')

read -ra list <<< $(
    # build a list of urls
    printf 'https://repology.org/badge/latest-versions/%s.svg?header= ' "${tmp_pkg[@]}"
)

while read -r line; do
    # parse svgs
    [[ ${line##*middle\">} =~ ([^<, ]+) ]]

    var=${BASH_REMATCH[1]}
    pkg=${tmp_pkg[i]}
    cur=${tmp_ver[i]}
    ((++i))

    case $var in
        -) n_ver+=("$pkg : $cur -> $var");;
        "$cur") ;; # do nothing
        *) y_ver+=("$pkg : $cur -> $var")
    esac
done <<< $(curl -w '\n' -s "${list[@]}")

display y_ver
display n_ver
